  !!!_name_!!!:
    env:
        DIST_ID: !!!_id_!!!
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

