  !!!_name_!!!:
    env:
        DIST_ID: !!!_id_!!!
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

