name: ToolchainsRelease

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build All
      run: ./build-docker-all-uncached.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: "docker/distros/*/*.tar.*"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      run: |
        for f in docker/distros/*/*.tar.* ;\
        do \
            filename=$(basename $f) ;\
            curl --request POST \
            --url ${{ steps.create_release.outputs.upload_url }}?name=$filename \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/gzip' \
            --form "data=@$f" ;\
        done
