name: ToolchainsRelease

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    #- uses: actions/checkout@v1
    #  with:
    #    ref: ${{ steps.get_tag_name.outputs.VERSION }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: ./build-docker-all.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: "*.tar.gz"
