name: ToolchainsRelease

on:
  push:
    tags:
    - 'v*'

jobs:

  armv6_1136js-zoop-linux-gnueabi_archlinux:
    env:
        DIST_ID: armv6_1136js-zoop-linux-gnueabi
        WKSP_ID: archlinux
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-androideabi_archlinux:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-androideabi
        WKSP_ID: archlinux
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-gnueabi_archlinux:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-gnueabi
        WKSP_ID: archlinux
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a9-zoop-linux-gnueabihf_archlinux:
    env:
        DIST_ID: armv7a_cortex_a9-zoop-linux-gnueabihf
        WKSP_ID: archlinux
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv6_1136js-zoop-linux-gnueabi_centos7:
    env:
        DIST_ID: armv6_1136js-zoop-linux-gnueabi
        WKSP_ID: centos7
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-androideabi_centos7:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-androideabi
        WKSP_ID: centos7
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-gnueabi_centos7:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-gnueabi
        WKSP_ID: centos7
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a9-zoop-linux-gnueabihf_centos7:
    env:
        DIST_ID: armv7a_cortex_a9-zoop-linux-gnueabihf
        WKSP_ID: centos7
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv6_1136js-zoop-linux-gnueabi_fedora29:
    env:
        DIST_ID: armv6_1136js-zoop-linux-gnueabi
        WKSP_ID: fedora29
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-androideabi_fedora29:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-androideabi
        WKSP_ID: fedora29
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-gnueabi_fedora29:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-gnueabi
        WKSP_ID: fedora29
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a9-zoop-linux-gnueabihf_fedora29:
    env:
        DIST_ID: armv7a_cortex_a9-zoop-linux-gnueabihf
        WKSP_ID: fedora29
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv6_1136js-zoop-linux-gnueabi_gentoo-amd64:
    env:
        DIST_ID: armv6_1136js-zoop-linux-gnueabi
        WKSP_ID: gentoo-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-androideabi_gentoo-amd64:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-androideabi
        WKSP_ID: gentoo-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-gnueabi_gentoo-amd64:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-gnueabi
        WKSP_ID: gentoo-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a9-zoop-linux-gnueabihf_gentoo-amd64:
    env:
        DIST_ID: armv7a_cortex_a9-zoop-linux-gnueabihf
        WKSP_ID: gentoo-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv6_1136js-zoop-linux-gnueabi_mint19-amd64:
    env:
        DIST_ID: armv6_1136js-zoop-linux-gnueabi
        WKSP_ID: mint19-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-androideabi_mint19-amd64:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-androideabi
        WKSP_ID: mint19-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-gnueabi_mint19-amd64:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-gnueabi
        WKSP_ID: mint19-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a9-zoop-linux-gnueabihf_mint19-amd64:
    env:
        DIST_ID: armv7a_cortex_a9-zoop-linux-gnueabihf
        WKSP_ID: mint19-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv6_1136js-zoop-linux-gnueabi_ubuntu16_04:
    env:
        DIST_ID: armv6_1136js-zoop-linux-gnueabi
        WKSP_ID: ubuntu16.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-androideabi_ubuntu16_04:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-androideabi
        WKSP_ID: ubuntu16.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-gnueabi_ubuntu16_04:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-gnueabi
        WKSP_ID: ubuntu16.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a9-zoop-linux-gnueabihf_ubuntu16_04:
    env:
        DIST_ID: armv7a_cortex_a9-zoop-linux-gnueabihf
        WKSP_ID: ubuntu16.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv6_1136js-zoop-linux-gnueabi_ubuntu18_04:
    env:
        DIST_ID: armv6_1136js-zoop-linux-gnueabi
        WKSP_ID: ubuntu18.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-androideabi_ubuntu18_04:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-androideabi
        WKSP_ID: ubuntu18.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a7-zoop-linux-gnueabi_ubuntu18_04:
    env:
        DIST_ID: armv7a_cortex_a7-zoop-linux-gnueabi
        WKSP_ID: ubuntu18.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  armv7a_cortex_a9-zoop-linux-gnueabihf_ubuntu18_04:
    env:
        DIST_ID: armv7a_cortex_a9-zoop-linux-gnueabihf
        WKSP_ID: ubuntu18.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: docker/noninteractive-build.sh ${DIST_ID} ${WKSP_ID}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: docker/distros/*/*/*.tar.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

