name: ToolchainsRelease

on:
  push:
    tags:
    - 'v*'

jobs:

  archlinux:
    env:
        DIST_ID: archlinux
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

  centos7:
    env:
        DIST_ID: centos7
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

  fedora29:
    env:
        DIST_ID: fedora29
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

  gentoo-amd64:
    env:
        DIST_ID: gentoo-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

  mint19-amd64:
    env:
        DIST_ID: mint19-amd64
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

  ubuntu16_04:
    env:
        DIST_ID: ubuntu16.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

  ubuntu18_04:
    env:
        DIST_ID: ubuntu18.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./build-docker-${DIST_ID}.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: true
        automatic_release_tag: latest
        files: |
          docker/distros/*/*.tar.*

